#!/usr/bin/env python3
"""Bet builder reel - one fixture, three legs, cut to the beat.

    python3 bbreel.py                          # best upcoming fixture, both brands
    python3 bbreel.py --brand tippsarena --n 3
    python3 bbreel.py --fixture 1517 --vo

WHAT CHANGED FROM THE FIRST VERSION, AND WHY.

His verdict on it was "boring, basic, nothing from this will get over 50 views".
Three things were actually wrong, and only one of them was the design.

1. THE PICK TYPE. The old reel was a correct score. A correct score has exactly
   one thing to reveal, at the end, so there is nothing to build - which is why
   the progress bar felt bolted on. A bet builder has three legs, so the bar IS
   the content: three rungs, three reveals, and the viewer can see how many are
   left. That is the anticipation he asked for, and it comes free with the
   right pick type. The legs come from tippsarena.com's own `ta_markets` meta
   (see bbtips.py) so the video cannot contradict the page it drives traffic to.

2. THE CLOCK. The old reel was cut to the narration - segment lengths were
   whatever the voice took. A video cut to a voice reads as a slideshow with
   commentary. This one is cut to a 150 bpm bed generated by music.py, and at
   150 bpm / 30 fps a beat is EXACTLY 12 frames, so every cut, every caption
   and every rung lands on a beat with no rounding at all. That is most of the
   difference between "fast" and "boring".

3. THE VOICE. He called the German read dead, and measuring it agreed: the
   pitch spread of thorsten-high is 2.9 semitones against 3.7 for the most
   expressive alternative that stays intelligible. But the honest fix is that
   this format does not need a voice - the pick has to be readable in silence
   anyway (his words), and most reels in the reference feed carry music only.
   So narration is now OFF by default and available with --vo.

THE FOOTAGE. `broll/custom/` is checked first and used exclusively if it has
anything in it. Drop his own licensed match clips there and they become the
footage with no code change; nothing else needs touching. The fallback stays
royalty-free (Coverr / Mixkit) rather than broadcast.
"""
from __future__ import annotations

import argparse
import json
import math
import pathlib
import subprocess
import wave

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter

import bbtips as B
import music as M
import narrate as N
import poster as P
import tips_video as T

W, H = 1080, 1920
FPS = 30
BPM = 150.0
#: 60/150 = 0.4 s, and 0.4 s at 30 fps is 12 frames on the nose. Every timing
#: in this file is an integer number of these, so nothing is ever rounded onto
#: a frame it does not belong on.
FPB = 12
BEAT = FPB / FPS

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT / "out" / "bbreels"
SCRATCH = N.VENV.parent
BROLL = SCRATCH / "broll"

#: bar -> what is on screen. 13 bars, 20.8 s. Short on purpose: the reference
#: feed runs 15-25 s and the drop-off past 25 is the whole game.
BARS = 13
SEG = [("hook", 0, 8), ("fixture", 8, 4), ("leg", 12, 8), ("leg", 20, 8),
       ("leg", 28, 8), ("conf", 36, 8), ("cta", 44, 8)]

#: Where the picture cuts, in beats. Two fast ones over the hook, then a
#: steady four-beat cut - 1.6 s a shot, which is quick without being a strobe.
CUTS = [0, 2, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48]

CARD_Y = 292
LAD_X, LAD_Y = 52, 812
LAD_W, LAD_STEP, LAD_H = 476, 150, 128
CAP_Y = 1372

CAP_FILL = {"tippsarena": (255, 110, 3), "luxtipps": (34, 255, 85)}

#: Rotated by fixture id so a week of these is not the same two seconds
#: fourteen times. All of them are curiosity, none of them is a promise -
#: "the easiest money today" is the one line that turns a creative for a
#: licensed gambling brand into a compliance problem.
HOOKS = {
    "de": [("DAS KLINGT", "VERRÜCKT"), ("MEIN BESTER", "TIPP HEUTE"),
           ("DEN HIER", "LIEBE ICH"), ("DAS MUSST", "DU SEHEN"),
           ("SCHAU DIR", "DAS AN")],
    "en": [("THIS SOUNDS", "CRAZY"), ("MY BEST", "PICK TODAY"),
           ("I LOVE", "THIS ONE"), ("YOU NEED", "TO SEE THIS"),
           ("LOOK AT", "THIS ONE")],
}

STR = {
    "de": {"three": "DREI TIPPS", "three_say": "Drei Tipps",
           "all3": "ALLE DREI", "one": "IN EINER WETTE",
           "conf": "KONFIDENZ", "cta1": "TÄGLICH NEUE TIPPS",
           "cta2": "MEHR TIPPS IN BIO", "combo": "KOMBI"},
    "en": {"three": "THREE PICKS", "three_say": "Three picks",
           "all3": "ALL THREE", "one": "IN ONE BET",
           "conf": "CONFIDENCE", "cta1": "NEW PICKS DAILY",
           "cta2": "MORE PICKS IN BIO", "combo": "BUILDER"},
}


# ------------------------------------------------------------------- the plan
def beats(fx: B.Fixture, lang: str) -> dict:
    """Everything that happens, in beats. No pixels and no audio yet.

    Keeping this separate is what makes the video checkable: verify_bbreel.py
    reads this structure back out of the manifest and asserts against the
    encoded file, rather than trusting that the renderer did what it said.
    """
    s = STR[lang]
    hook = HOOKS[lang][fx.id % len(HOOKS[lang])]
    caps, rungs, hits = [], [], []

    def cap(at, dur, text, size="big"):
        caps.append({"at": at, "off": at + dur, "text": text, "size": size})

    cap(0, 2, hook[0])
    cap(2, 2, hook[1])
    cap(4, 4, fx.league.upper(), "mid")
    cap(8, 4, s["three"])

    for i, leg in enumerate(fx.legs):
        b0 = 12 + i * 8
        # Two cards, not one per word. leg.hero breaks the pick where it means
        # something; a card reading only "1X" was the first version and it is
        # not a bet anybody can read off the screen.
        step = 5.0 / len(leg.hero)
        for k, tok in enumerate(leg.hero):
            cap(round((b0 + k * step) * 2) / 2, step, tok)
        light = round((b0 + 5.0) * 2) / 2
        # The rung lights AFTER the whole leg has been shown, never before it.
        # A bar that fills early is the same defect as a card that reveals
        # early, in the one place a card check would not look.
        rungs.append(light)
        hits.append(light)
        if leg.pct:
            cap(light, (b0 + 8) - light, f"{leg.pct}%", "pct")

    cap(36, 2, s["all3"], "mid")
    cap(38, 2, s["one"], "mid")
    cap(40, 4, f"{fx.conf}%", "pct")
    hits.append(40)
    cap(44, 4, s["cta1"], "mid")
    cap(48, 4, s["cta2"], "mid")
    return {"caps": caps, "rungs": rungs, "hits": hits, "hook": list(hook)}


def narration(fx: B.Fixture, lang: str) -> dict:
    """One spoken line per beat-segment, for --vo. Optional by design.

    Each line is placed at the START of its segment and must FIT inside it;
    fits() reports any that does not rather than letting the voice talk over
    the next card. Nothing on screen is timed off these words - the beat grid
    is the clock - so a line running slightly short is silence, not drift.
    """
    s = STR[lang]
    lines = {"n0": f"{B.club(fx.home_short, lang)} "
                   f"{'gegen' if lang == 'de' else 'against'} "
                   f"{B.club(fx.away_short, lang)}.",
             "n1": s["three_say"] + "."}
    for i, leg in enumerate(fx.legs):
        lines[f"l{i}"] = leg.say + "."
    conf = B._num_say(str(fx.conf), lang) if fx.conf else None
    if conf:
        lines["nc"] = (f"{conf} Prozent Konfidenz." if lang == "de"
                       else f"{conf} percent confidence.")
    return lines


#: Which beat each narration line starts on.
VO_AT = {"n1": 8, "l0": 12, "l1": 20, "l2": 28, "nc": 36}


def fits(clips: dict, room: dict) -> list[str]:
    """Which spoken lines are longer than the segment they sit in."""
    bad = []
    for key, beats_ in room.items():
        if key in clips and clips[key]["dur"] > beats_ * BEAT - 0.15:
            bad.append(f"{key}: {clips[key]['dur']:.2f}s of speech in "
                       f"{beats_ * BEAT:.2f}s of picture")
    return bad


# -------------------------------------------------------------------- glyphs
def glyph(kind: str, size: int, fill, dim: bool = False) -> Image.Image:
    """The little mark on a rung. Drawn, not an emoji - the project font has no
    emoji coverage and a missing glyph renders as a blank box, which on the one
    element that is supposed to say "goals" is worse than no icon at all."""
    key = ("bbg", kind, size, fill, dim)
    if key in P._cache:
        return P._cache[key]
    im = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    c = size / 2
    ink = fill if not dim else (150, 158, 168)
    if kind == "goal":
        d.ellipse((3, 3, size - 4, size - 4), fill=ink)
        r = size * 0.17
        d.regular_polygon((c, c, r), 5, rotation=0, fill=(12, 14, 18))
        for a in range(5):
            x = c + math.cos(math.radians(a * 72 - 90)) * size * 0.32
            y = c + math.sin(math.radians(a * 72 - 90)) * size * 0.32
            d.regular_polygon((x, y, r * 0.62), 5, rotation=36,
                              fill=(12, 14, 18))
    elif kind == "card":
        d.rounded_rectangle((size * 0.26, size * 0.12, size * 0.74,
                             size * 0.88), size * 0.10, fill=ink)
    elif kind == "corner":
        d.line([(size * 0.30, size * 0.10), (size * 0.30, size * 0.90)],
               fill=ink, width=max(3, size // 12))
        d.polygon([(size * 0.34, size * 0.16), (size * 0.84, size * 0.32),
                   (size * 0.34, size * 0.48)], fill=ink)
    elif kind == "shot":
        for i, r in enumerate((0.46, 0.30, 0.14)):
            d.ellipse((c - size * r, c - size * r, c + size * r, c + size * r),
                      outline=ink, width=max(3, size // 11),
                      fill=ink if i == 2 else None)
    elif kind == "btts":
        d.ellipse((size * 0.06, c - size * 0.20, size * 0.46, c + size * 0.20),
                  fill=ink)
        d.ellipse((size * 0.54, c - size * 0.20, size * 0.94, c + size * 0.20),
                  fill=ink)
    else:                                   # shield
        d.polygon([(c, size * 0.08), (size * 0.88, size * 0.26),
                   (size * 0.78, size * 0.80), (c, size * 0.94),
                   (size * 0.22, size * 0.80), (size * 0.12, size * 0.26)],
                  fill=ink)
    P._cache[key] = im
    return im


def _wrap(text: str, f, room: int) -> list[str]:
    out, line = [], ""
    for w in text.split():
        t = f"{line} {w}".strip()
        if f.getlength(t) <= room or not line:
            line = t
        else:
            out.append(line)
            line = w
    if line:
        out.append(line)
    return out


def rung(b: T.Brand, leg: B.Leg, live: bool) -> Image.Image:
    """One step of the progress bar, lit or not.

    THE UNLIT STATE CONTAINS NO TEXT. Not blurred text, not dimmed text -
    none. Blurring 34pt type does not hide it; it reads perfectly and hands
    the viewer the answer the whole video is built to reveal. So an unlit rung
    is a grey icon and two placeholder bars, the way a page looks before its
    content loads, and the words only ever exist in the lit copy.
    """
    key = ("bbrung", b.key, leg.disp, leg.pct, live)
    if key in P._cache:
        return P._cache[key]
    im = Image.new("RGBA", (LAD_W, LAD_H), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    dark = b.style == "dark"
    d.rounded_rectangle((0, 0, LAD_W - 1, LAD_H - 1), 26,
                        fill=(9, 11, 15, 214) if dark else (243, 240, 232, 224))
    if live:
        d.rounded_rectangle((0, 0, 7, LAD_H - 1), 4, fill=b.accent)

    gs = 62
    im.alpha_composite(glyph(leg.icon, gs, b.accent, dim=not live),
                       (26, (LAD_H - gs) // 2))
    x = 26 + gs + 20
    ink = (247, 250, 253) if dark else T.CHAR
    sub = (150, 163, 178) if dark else (120, 116, 106)

    if not live:
        # skeleton, deliberately not words
        d.rounded_rectangle((x, 40, x + 250, 58), 9, fill=(255, 255, 255, 46))
        d.rounded_rectangle((x, 70, x + 160, 88), 9, fill=(255, 255, 255, 32))
        P._cache[key] = im
        return im

    pct = f"{leg.pct}%" if leg.pct else ""
    pf = P.font(38)
    pw = pf.getlength(pct) + 20 if pct else 0
    room = LAD_W - x - 22 - pw
    size = 38
    f = P.font(size)
    while size > 22:
        rows = _wrap(leg.disp, f, room)
        if len(rows) <= 2:
            break
        size -= 2
        f = P.font(size)
    rows = _wrap(leg.disp, f, room)[:2]
    y = LAD_H // 2 - (len(rows) - 1) * (size + 6) // 2
    for r in rows:
        d.text((x, y), r, font=f, fill=ink, anchor="lm")
        y += size + 6
    if pct:
        d.text((LAD_W - 22, LAD_H // 2), pct, font=pf, fill=b.accent,
               anchor="rm")
    P._cache[key] = im
    return im


def match_card(b: T.Brand, fx: B.Fixture) -> Image.Image:
    """Pinned from the moment the fixture lands and never taken away, so the
    match is answerable at any frame the viewer happens to scroll in on."""
    key = ("bbcard", b.key, fx.id)
    if key in P._cache:
        return P._cache[key]
    cw, ch = W - 104, 214
    im = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    dark = b.style == "dark"
    d.rounded_rectangle((0, 0, cw - 1, ch - 1), 30,
                        fill=(9, 11, 15, 226) if dark else (243, 240, 232, 232))
    ink = (247, 250, 253) if dark else T.CHAR
    sub = (150, 163, 178) if dark else (120, 116, 106)

    cs = 112
    for i, url in enumerate((fx.home_logo, fx.away_logo)):
        disc = Image.new("RGBA", (cs, cs), (0, 0, 0, 0))
        dd = ImageDraw.Draw(disc)
        dd.ellipse((0, 0, cs - 1, cs - 1), fill=b.accent)
        dd.ellipse((5, 5, cs - 6, cs - 6), fill=(252, 252, 252))
        p = B.crest(url)
        if p:
            try:
                c = Image.open(p).convert("RGBA")
                k = int(cs * 0.62)
                c = c.resize((k, k), Image.LANCZOS)
                disc.paste(c, ((cs - k) // 2, (cs - k) // 2), c)
            except Exception:                             # noqa: BLE001
                pass
        im.alpha_composite(disc, (24 + int(i * cs * 0.74), (ch - cs) // 2))

    x = 24 + int(cs * 1.74) + 22
    name = f"{fx.home_short.upper()}  –  {fx.away_short.upper()}"
    size = 52
    while P.font(size).getlength(name) > cw - x - 26 and size > 26:
        size -= 2
    d.text((x, 82), name, font=P.font(size), fill=ink, anchor="lm")
    when = f"{fx.kickoff:%H:%M}  ·  {fx.league.upper()}"
    size = 32
    while P.font(size).getlength(when) > cw - x - 26 and size > 18:
        size -= 2
    d.text((x, 140), when, font=P.font(size), fill=sub, anchor="lm")
    P._cache[key] = im
    return im


_cap: dict = {}
SIZES = {"big": 176, "mid": 104, "pct": 240}


def word(text: str, fill, size_key: str) -> Image.Image:
    key = (text, fill, size_key)
    if key in _cap:
        return _cap[key]
    size, pad = SIZES[size_key], 34
    f = P.font(size)
    while f.getlength(text) > 900 and size > 44:
        size -= 6
        f = P.font(size)
    box = f.getbbox(text, stroke_width=17)
    im = Image.new("RGBA", (box[2] - box[0] + pad * 2,
                            box[3] - box[1] + pad * 2), (0, 0, 0, 0))
    ImageDraw.Draw(im).text((pad - box[0], pad - box[1]), text, font=f,
                            fill=fill + (255,), stroke_width=17,
                            stroke_fill=(0, 0, 0, 255))
    sh = Image.new("RGBA", im.size, (0, 0, 0, 0))
    sh.putalpha(im.getchannel("A").filter(ImageFilter.GaussianBlur(13)))
    out = Image.new("RGBA", im.size, (0, 0, 0, 0))
    out.alpha_composite(sh, (0, 13))
    out.alpha_composite(im)
    _cap[key] = out
    return out


def _alpha(im: Image.Image, a: float) -> Image.Image:
    out = im.copy()
    out.putalpha(out.getchannel("A").point(lambda v: int(v * a)))
    return out


PB_W, PB_H = 560, 20


def pct_bar(b: T.Brand, pct: int, fill_to: float) -> Image.Image:
    """The bar under a percentage. Fills to `fill_to` of the true value."""
    key = ("bbpb", b.key, pct, round(fill_to, 2))
    if key in P._cache:
        return P._cache[key]
    im = Image.new("RGBA", (PB_W, PB_H), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((0, 0, PB_W - 1, PB_H - 1), PB_H // 2,
                        fill=(0, 0, 0, 150), outline=(255, 255, 255, 70),
                        width=2)
    w = int((PB_W - 6) * (pct / 100.0) * P.ease_out(fill_to))
    if w > PB_H:
        d.rounded_rectangle((3, 3, 3 + w, PB_H - 4), (PB_H - 6) // 2,
                            fill=b.accent)
    P._cache[key] = im
    return im


def furniture(b: T.Brand) -> Image.Image:
    g = Image.new("L", (W, H), 0)
    gd = ImageDraw.Draw(g)
    for y in range(H):
        top = max(0.0, 1 - y / 640) * 158
        bot = max(0.0, (y - 980) / (H - 980)) * 128
        gd.line([(0, y), (W, y)], fill=int(min(205, top + bot)))
    col = Image.new("L", (W, H), 0)
    cd = ImageDraw.Draw(col)
    for x in range(600):
        cd.line([(x, LAD_Y - 70), (x, LAD_Y + 2 * LAD_STEP + LAD_H + 70)],
                fill=int(88 * (1 - x / 600)))
    col = col.filter(ImageFilter.GaussianBlur(70))
    g.paste(ImageChops.lighter(g, col))
    im = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    im.paste((0, 0, 0, 255), (0, 0, W, H), g)
    im.alpha_composite(b.disc(96), (56, 128))
    return im


# -------------------------------------------------------------------- footage
def clip_pool() -> list[pathlib.Path]:
    """His own clips if he has sent any, otherwise the royalty-free set.

    `broll/custom/` wins outright rather than being mixed in: half a reel of
    real match footage and half of a stock warm-up looks like a mistake, not a
    style. Drop files in, they are the footage; take them out, it falls back.
    """
    custom = sorted((BROLL / "custom").glob("*.mp4"))
    if custom:
        return custom
    pool = sorted(p for p in BROLL.glob("*.mp4"))
    if not pool:
        raise SystemExit(f"no footage in {BROLL} - run fetch_broll.sh, or put "
                         f"his clips in {BROLL / 'custom'}")
    return pool


OVER = 1.26


def bg_frames(src: pathlib.Path, n: int, seed: int):
    ow, oh = int(W * OVER), int(H * OVER)
    #: A different second of the clip each time it is reused, so a pool of four
    #: files under fourteen shots does not read as four repeats.
    start = (seed * 3.7) % 9.0
    p = subprocess.Popen(
        ["ffmpeg", "-v", "error", "-ss", f"{start:.2f}", "-stream_loop", "-1",
         "-i", str(src), "-an",
         "-vf", f"fps={FPS},crop=ih*9/16:ih,scale={ow}:{oh},"
                # Lifted, not darkened. The gradient in furniture() already
                # takes the top and bottom down by a lot for the text to sit
                # on; darkening the source as well left the middle of the
                # frame - the only part actually showing football - muddy.
                "eq=brightness=0.03:saturation=1.24:contrast=1.12",
         "-frames:v", str(n), "-f", "rawvideo", "-pix_fmt", "rgb24", "-"],
        stdout=subprocess.PIPE)
    size = ow * oh * 3
    try:
        for _ in range(n):
            raw = p.stdout.read(size)
            if len(raw) < size:
                break
            yield np.frombuffer(raw, np.uint8).reshape(oh, ow, 3)
    finally:
        p.stdout.close()
        p.wait()


# ---------------------------------------------------------------------- audio
def track(fx: B.Fixture, lang: str, pl: dict, vo: bool,
          path: pathlib.Path) -> tuple[pathlib.Path, list[str]]:
    """Bed + hits (+ narration). Returns the wav and anything that did not fit."""
    bed = M.build(BPM, BARS)
    sr = bed.sr
    warn: list[str] = []

    for at in pl["hits"]:
        bed.put(M.impact(), at * BEAT - 0.02, 0.55)
        bed.put(M.riser(0.55), at * BEAT - 0.55, 0.30)
    for c in CUTS[1:]:
        bed.put(M.whoosh(), c * BEAT - 0.16, 0.24)

    mix = bed.mix.copy()
    if vo:
        lines = narration(fx, lang)
        clips = N._synth(lang, lines, f"bbreel-{fx.id}-{lang}")
        room = {"n1": 4, "l0": 8, "l1": 8, "l2": 8, "nc": 8}
        warn = fits(clips, room)
        # The bed steps back under the voice rather than the voice being
        # pushed over it - a bed at full level with a TTS read on top is the
        # single most common way this kind of video ends up unintelligible.
        for key, at in VO_AT.items():
            if key not in clips:
                continue
            with wave.open(clips[key]["file"]) as w:
                a = np.frombuffer(w.readframes(w.getnframes()), np.int16)
                vsr = w.getframerate()
            if vsr != sr:
                x = np.interp(np.arange(0, len(a), vsr / sr),
                              np.arange(len(a)), a).astype(np.float32)
            else:
                x = a.astype(np.float32)
            x /= 32768.0
            i = int(at * BEAT * sr)
            n = min(len(x), len(mix) - i)
            if n <= 0:
                continue
            duck = np.ones(n, dtype=np.float32) * 0.42
            mix[i:i + n] = mix[i:i + n] * duck + x[:n] * 1.5

    mix = np.tanh(mix * 1.1).astype(np.float32)
    M.write(mix, path)
    return path, warn


# ----------------------------------------------------------------------- bake
def render(brand_key: str, fx: B.Fixture, vo: bool) -> pathlib.Path:
    b = T.BRANDS[brand_key]
    lang = b.lang
    pl = beats(fx, lang)
    total = BARS * 4 * FPB
    OUT.mkdir(parents=True, exist_ok=True)
    wav, warn = track(fx, lang, pl, vo,
                      OUT / "vo" / f"{brand_key}-{fx.slug}.wav")
    for w in warn:
        print(f"  !! narration overruns its segment - {w}")

    manifest = {"fps": FPS, "bpm": BPM, "fpb": FPB, "bars": BARS,
                "frames": total, "lang": lang, "brand": brand_key,
                "fixture": {"id": fx.id, "home": fx.home_short,
                            "away": fx.away_short, "league": fx.league,
                            "kickoff": fx.kickoff.isoformat(),
                            "conf": fx.conf, "url": fx.url,
                            "legs": [{"disp": g.disp, "say": g.say,
                                      "pct": g.pct, "icon": g.icon}
                                     for g in fx.legs]},
                "cuts": CUTS, "vo": vo, **pl}
    (OUT / "vo" / f"{brand_key}-{fx.slug}.json").write_text(
        json.dumps(manifest, indent=1, ensure_ascii=False), encoding="utf-8")

    out = OUT / f"{brand_key}-bb-{fx.slug}.mp4"
    enc = subprocess.Popen(
        ["ffmpeg", "-y", "-loglevel", "error",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}",
         "-framerate", str(FPS), "-i", "-", "-i", str(wav),
         "-c:a", "aac", "-b:a", "160k", "-shortest",
         "-c:v", "libx264", "-preset", "medium", "-crf", "20",
         "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(out)],
        stdin=subprocess.PIPE)

    fur = furniture(b)
    fill = CAP_FILL[brand_key]
    card = match_card(b, fx)
    rows = [(rung(b, g, False), rung(b, g, True)) for g in fx.legs]
    pool = clip_pool()
    ow, oh = int(W * OVER), int(H * OVER)
    slack = (ow - W, oh - H)

    shots = [(CUTS[i], CUTS[i + 1] - CUTS[i]) for i in range(len(CUTS) - 1)]
    shots.append((CUTS[-1], BARS * 4 - CUTS[-1]))
    hits = [h * BEAT for h in pl["hits"]]

    for si, (b0, nb) in enumerate(shots):
        n = nb * FPB
        src = pool[si % len(pool)]
        gen, last = bg_frames(src, n, si), None
        d0, d1 = (0.10, 0.90) if si % 2 == 0 else (0.90, 0.10)
        for k in range(n):
            arr = last = next(gen, last)
            if arr is None:
                raise SystemExit(f"shot {si}: no frames from {src.name}")
            f_abs = b0 * FPB + k
            t = f_abs / FPS
            u = k / max(n - 1, 1)

            # --- camera: drift, plus a decaying shake off the nearest hit
            a = d0 + (d1 - d0) * u
            sx, sy = 0, 0
            for ht in hits:
                dt = t - ht
                if 0 <= dt < 0.34:
                    e = (1 - dt / 0.34) ** 2
                    sx += int(math.sin(dt * 96) * 26 * e)
                    sy += int(math.cos(dt * 78) * 18 * e)
            x = min(max(int(slack[0] * a) + sx, 0), slack[0])
            y = min(max(int(slack[1] * (1 - a)) + sy, 0), slack[1])
            frame = Image.fromarray(arr[y:y + H, x:x + W]).convert("RGBA")
            # The impact flash goes on the FOOTAGE, before any graphic is laid
            # over it. Composited last and in the brand colour it washed the
            # entire frame - card, ladder and caption included - orange for
            # three frames, which reads as a rendering fault rather than a hit.
            # White, weaker, shorter, and underneath everything that has to
            # stay legible.
            for ht in hits:
                dt = t - ht
                if 0 <= dt < 0.11:
                    k2 = (1 - dt / 0.11) ** 2
                    frame.alpha_composite(
                        Image.new("RGBA", (W, H), (255, 255, 255,
                                                   int(58 * k2))))
                    break
            frame.alpha_composite(fur)

            # --- the match card, from the fixture bar onward
            if f_abs >= 8 * FPB:
                s = min(1.0, (t - 8 * BEAT) / 0.24)
                dy = int((1 - P.ease_out(s)) * -80)
                lay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
                lay.alpha_composite(card, (52, CARD_Y + dy))
                if s < 1:
                    lay.putalpha(lay.getchannel("A").point(
                        lambda v: int(v * s)))
                frame.alpha_composite(lay)

                for ri, (dim, live) in enumerate(rows):
                    ry = LAD_Y + ri * LAD_STEP
                    lt = pl["rungs"][ri] * BEAT
                    prog = (t - lt) / 0.26
                    if prog <= 0:
                        frame.alpha_composite(_alpha(dim, s), (LAD_X, ry))
                    elif prog >= 1:
                        frame.alpha_composite(live, (LAD_X, ry))
                    else:
                        # out, then in. The two states carry different pixels
                        # entirely - a skeleton and a sentence - so crossing
                        # them over draws both and reads as a fault.
                        if prog < 0.4:
                            frame.alpha_composite(
                                _alpha(dim, 1 - P.ease_out(prog / 0.4)),
                                (LAD_X, ry))
                        else:
                            e = P.ease_out((prog - 0.4) / 0.6)
                            sc = 1 + 0.09 * (1 - e)
                            im = live.resize((int(live.width * sc),
                                              int(live.height * sc)),
                                             Image.BILINEAR)
                            frame.alpha_composite(
                                _alpha(im, e),
                                (LAD_X - (im.width - live.width) // 2,
                                 ry - (im.height - live.height) // 2))

            # --- captions
            for c in pl["caps"]:
                if not (c["at"] * BEAT <= t < c["off"] * BEAT):
                    continue
                im = word(c["text"], fill, c["size"])
                e = (t - c["at"] * BEAT) / 0.13
                sc = (0.66 + 0.46 * P.ease_out(e / 0.7) if e < 0.7
                      else 1.12 - 0.12 * P.ease_out(min(1.0, (e - 0.7) / 0.3)))
                if abs(sc - 1) > 0.005:
                    im = im.resize((max(1, int(im.width * sc)),
                                    max(1, int(im.height * sc))),
                                   Image.BILINEAR)
                cy = CAP_Y if c["size"] != "pct" else CAP_Y + 40
                frame.alpha_composite(im, (max(0, W // 2 - im.width // 2),
                                           cy - im.height // 2))
                if c["size"] == "pct":
                    # The number is CORRECT from the first frame it exists;
                    # what animates is the bar under it. The first version
                    # counted the digits up from zero, which put a frame
                    # reading "0%" on screen under a betting pick - a figure
                    # that is not merely ugly but wrong, and would have been
                    # the thumbnail if the grid ever picked that frame.
                    # A bar filling cannot be misread as a claim.
                    frame.alpha_composite(
                        pct_bar(b, int(c["text"].rstrip("%")),
                                min(1.0, (t - c["at"] * BEAT) / 0.50)),
                        ((W - PB_W) // 2, cy + im.height // 2 + 26))
                break

            enc.stdin.write(frame.convert("RGB").tobytes())

    enc.stdin.close()
    enc.wait()
    print(f"  {out.name}  {total}f  {total / FPS:.1f}s  "
          f"{len(fx.legs)} legs  {fx.conf}%")
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--brand", choices=list(T.BRANDS) + ["both"], default="both")
    ap.add_argument("--n", type=int, default=1, help="how many fixtures")
    ap.add_argument("--fixture", type=int, help="a specific post id")
    ap.add_argument("--vo", action="store_true", help="add a spoken layer")
    ap.add_argument("--all", action="store_true",
                    help="allow fixtures that have already kicked off")
    a = ap.parse_args()
    for k in (list(T.BRANDS) if a.brand == "both" else [a.brand]):
        lang = T.BRANDS[k].lang
        fxs = B.load(lang, upcoming=not a.all)
        if a.fixture:
            fxs = [f for f in fxs if f.id == a.fixture]
        if not fxs:
            raise SystemExit("no upcoming fixture with a usable combo")
        print(f"{k}:")
        for fx in fxs[:a.n]:
            render(k, fx, a.vo)


if __name__ == "__main__":
    main()
