#!/usr/bin/env python3
"""Bet builder reel - one fixture, three legs, cut to the beat.

    python3 bbreel.py                          # best upcoming fixture, both brands
    python3 bbreel.py --brand tippsarena --n 3
    python3 bbreel.py --fixture 1517 --vo
    python3 bbreel.py --bg motion --amount 500 # drawn background, other figure

WHAT CHANGED IN v3 (2 Sept, second round of his feedback).

He watched v2 and said the voice is dead, the stock clips suck, and the whole
thing does not hold a viewer - it needs a hook like "Easiest way to earn 1000€
today", and emojis next to the title.

  * THE HOOK is now three stacked lines held for two seconds, with the money
    figure at 250px in the middle - the largest thing in the reel. It is a
    table, rotated by fixture id, and the figure is --amount, so changing the
    whole hook is an argument rather than an edit. It also forced a real fix:
    the caption loop stopped at the first caption whose window contained the
    current frame, so a stacked hook would have drawn one line and dropped the
    other two without any error at all.
  * EMOJIS beside the closing chunk of each pick, keyed to the same market icon
    the rung below uses, plus one in the hook and one on the CTA. Composited
    from Noto Color Emoji rather than typed into the string: Lato has no
    coverage and would have drawn an outlined blank box.
  * THE VOICE is off unless you pass --vo, and v3 does not use it.
  * THE FOOTAGE. `--bg motion` draws the background instead - floodlit stadium,
    brand wash, a light sweep, a glow pulsing on the beat. No stock, no
    broadcast, nothing that can look cheap or get an account struck. `--bg
    clips` still uses broll/custom/ if he ever sends his own.
  * A PUNCH-IN on every cut and a TIPP n/3 badge, because "how many are left"
    should be answerable in a glance rather than by counting rungs.

WHAT CHANGED FROM THE FIRST VERSION, AND WHY.

His verdict on it was "boring, basic, nothing from this will get over 50 views".
Three things were actually wrong, and only one of them was the design.

1. THE PICK TYPE. The old reel was a correct score. A correct score has exactly
   one thing to reveal, at the end, so there is nothing to build - which is why
   the progress bar felt bolted on. A bet builder has three legs, so the bar IS
   the content: three rungs, three reveals, and the viewer can see how many are
   left. That is the anticipation he asked for, and it comes free with the
   right pick type. The legs come from tippsarena.com's own `ta_markets` meta
   (see bbtips.py) so the video cannot contradict the page it drives traffic to.

2. THE CLOCK. The old reel was cut to the narration - segment lengths were
   whatever the voice took. A video cut to a voice reads as a slideshow with
   commentary. This one is cut to a 150 bpm bed generated by music.py, and at
   150 bpm / 30 fps a beat is EXACTLY 12 frames, so every cut, every caption
   and every rung lands on a beat with no rounding at all. That is most of the
   difference between "fast" and "boring".

3. THE VOICE. He called the German read dead, and measuring it agreed: the
   pitch spread of thorsten-high is 2.9 semitones against 3.7 for the most
   expressive alternative that stays intelligible. But the honest fix is that
   this format does not need a voice - the pick has to be readable in silence
   anyway (his words), and most reels in the reference feed carry music only.
   So narration is now OFF by default and available with --vo.

THE FOOTAGE. `broll/custom/` is checked first and used exclusively if it has
anything in it. Drop his own licensed match clips there and they become the
footage with no code change; nothing else needs touching. The fallback stays
royalty-free (Coverr / Mixkit) rather than broadcast.
"""
from __future__ import annotations

import argparse
import json
import math
import pathlib
import subprocess
import wave

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter

import bbtips as B
import music as M
import narrate as N
import poster as P
import tips_video as T

W, H = 1080, 1920
FPS = 30
BPM = 150.0
#: 60/150 = 0.4 s, and 0.4 s at 30 fps is 12 frames on the nose. Every timing
#: in this file is an integer number of these, so nothing is ever rounded onto
#: a frame it does not belong on.
FPB = 12
BEAT = FPB / FPS

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT / "out" / "bbreels"
SCRATCH = N.VENV.parent
BROLL = SCRATCH / "broll"

#: bar -> what is on screen. 13 bars, 20.8 s. Short on purpose: the reference
#: feed runs 15-25 s and the drop-off past 25 is the whole game.
BARS = 13
SEG = [("hook", 0, 8), ("fixture", 8, 4), ("leg", 12, 8), ("leg", 20, 8),
       ("leg", 28, 8), ("conf", 36, 8), ("cta", 44, 8)]

#: Where the picture cuts, in beats. Two fast ones over the hook, then a
#: steady four-beat cut - 1.6 s a shot, which is quick without being a strobe.
CUTS = [0, 2, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48]

CARD_Y = 292
LAD_X, LAD_Y = 52, 812
LAD_W, LAD_STEP, LAD_H = 476, 150, 128
CAP_Y = 1372

CAP_FILL = {"tippsarena": (255, 110, 3), "luxtipps": (34, 255, 85)}

#: The hook: three stacked lines and an emoji, held for two seconds.
#:
#: The previous set was two words of curiosity - "DAS KLINGT / VERRÜCKT" - and
#: he was blunt that it does not stop a thumb. What he asked for by name is a
#: money line: "Easiest way to earn 1000€ today". So the middle line is the
#: figure, at 250px, and it is the largest thing that appears in the whole
#: reel.
#:
#: I told him once and it is written here rather than argued again: a stated
#: earnings figure is the line Meta and TikTok enforce hardest on gambling
#: creatives, and it is his account it lands on. He asked for it anyway, which
#: is his call to make. What that DOES change is the code: the amount is a
#: parameter (--amount), the lines are a table, and none of it is baked into a
#: render - so swapping the whole hook is one argument, not a rebuild.
#:
#: Rotated by fixture id, so a week of these is not the same two seconds
#: fourteen times over.
HOOKS = {
    "de": [("SO VERDIENST DU HEUTE", "{amount}", "SCHAU DIR DAS AN", "💰"),
           ("DER EINFACHSTE WEG ZU", "{amount}", "HEUTE ABEND", "🔥"),
           ("EIN SPIEL, DREI TIPPS", "{amount}", "SO GEHT'S", "🚨"),
           ("NICHT WEITERSCROLLEN", "{amount}", "MIT EINER KOMBI", "👀"),
           ("HEUTE ABEND MÖGLICH", "{amount}", "ICH ZEIG DIR WIE", "⚽")],
    "en": [("HOW TO MAKE TODAY", "{amount}", "WATCH THIS", "💰"),
           ("THE EASIEST WAY TO", "{amount}", "TONIGHT", "🔥"),
           ("ONE MATCH, THREE PICKS", "{amount}", "HERE'S HOW", "🚨"),
           ("DON'T SCROLL PAST", "{amount}", "ONE BET BUILDER", "👀"),
           ("POSSIBLE TONIGHT", "{amount}", "LET ME SHOW YOU", "⚽")],
}

#: German writes a thousands dot and puts the sign after the number; English
#: puts it in front and uses a comma. Getting this wrong is the kind of detail
#: that tells a viewer the account is not really theirs.
def money(amount: int, lang: str) -> str:
    return (f"{amount:,}".replace(",", ".") + " €" if lang == "de"
            else "€" + f"{amount:,}")

#: An emoji beside the pick, keyed off the same icon the rung uses, so the
#: caption and the ladder rung below it are talking about the same market.
#: He asked for these by name: "there have to be emojis next to the title".
LEG_EMOJI = {"goal": "⚽", "card": "🟨", "corner": "🚩", "shot": "🎯",
             "btts": "🥅", "shield": "🛡️"}

STR = {
    "de": {"three": "DREI TIPPS", "three_say": "Drei Tipps",
           "all3": "ALLE DREI", "one": "IN EINER WETTE",
           "conf": "KONFIDENZ", "cta1": "TÄGLICH NEUE TIPPS",
           "cta2": "MEHR TIPPS IN BIO", "combo": "KOMBI", "tip": "TIPP"},
    "en": {"three": "THREE PICKS", "three_say": "Three picks",
           "all3": "ALL THREE", "one": "IN ONE BET",
           "conf": "CONFIDENCE", "cta1": "NEW PICKS DAILY",
           "cta2": "MORE PICKS IN BIO", "combo": "BUILDER", "tip": "PICK"},
}


# ------------------------------------------------------------------- the plan
def beats(fx: B.Fixture, lang: str, amount: int = 1000) -> dict:
    """Everything that happens, in beats. No pixels and no audio yet.

    Keeping this separate is what makes the video checkable: verify_bbreel.py
    reads this structure back out of the manifest and asserts against the
    encoded file, rather than trusting that the renderer did what it said.

    Captions carry a `dy`. They used to be a single line at CAP_Y and only one
    could ever be on screen, which is why the hook could only be two words: a
    three-line hook is three captions at three offsets, up at eye level rather
    than down where the pick text lives.
    """
    s = STR[lang]
    hook = HOOKS[lang][fx.id % len(HOOKS[lang])]
    pre, mid, post, emo = hook
    mid = mid.format(amount=money(amount, lang))
    caps, rungs, hits = [], [], []

    def cap(at, dur, text, size="big", dy=0, emo=None):
        caps.append({"at": at, "off": at + dur, "text": text, "size": size,
                     "dy": dy, "emo": emo})

    # --- the hook: two seconds, three lines, held still ------------------
    # Held, not cut into pieces. A hook that changes every half-beat is read
    # as motion and not as a sentence, and this one has to be READ - it is the
    # only claim in the reel a viewer decides on before they have watched
    # anything. The picture underneath still cuts twice; the words do not.
    cap(0, 5, pre, "mid", dy=-330)
    cap(0, 5, mid, "hook", dy=-110)
    cap(0, 5, post, "mid", dy=110, emo=emo)
    # Beat 2, not beat 0. An impact placed at t=0 has its attack truncated by
    # the start of the file, so there is nothing for an onset detector to find
    # and the hit check fails on a sound that is genuinely there. Beat 2 is
    # also a planned cut, so the accent and the cut reinforce each other.
    hits.append(2)
    cap(5, 3, fx.league.upper(), "mid")
    cap(8, 4, s["three"])

    for i, leg in enumerate(fx.legs):
        b0 = 12 + i * 8
        # Two cards, not one per word. leg.hero breaks the pick where it means
        # something; a card reading only "1X" was the first version and it is
        # not a bet anybody can read off the screen.
        step = 5.0 / len(leg.hero)
        last = len(leg.hero) - 1
        for k, tok in enumerate(leg.hero):
            # The emoji goes on the LAST chunk only. On every chunk it reads as
            # decoration attached to nothing; on the closing one it lands with
            # the completed pick, which is the thing it is labelling.
            cap(round((b0 + k * step) * 2) / 2, step, tok,
                emo=LEG_EMOJI.get(leg.icon) if k == last else None)
        light = round((b0 + 5.0) * 2) / 2
        # The rung lights AFTER the whole leg has been shown, never before it.
        # A bar that fills early is the same defect as a card that reveals
        # early, in the one place a card check would not look.
        rungs.append(light)
        hits.append(light)
        if leg.pct:
            cap(light, (b0 + 8) - light, f"{leg.pct}%", "pct")

    cap(36, 2, s["all3"], "mid")
    cap(38, 2, s["one"], "mid")
    cap(40, 4, f"{fx.conf}%", "pct")
    hits.append(40)
    cap(44, 4, s["cta1"], "mid")
    cap(48, 4, s["cta2"], "mid", emo="📲")
    return {"caps": caps, "rungs": rungs, "hits": hits,
            "hook": [pre, mid, post, emo], "amount": amount}


def narration(fx: B.Fixture, lang: str) -> dict:
    """One spoken line per beat-segment, for --vo. Optional by design.

    Each line is placed at the START of its segment and must FIT inside it;
    fits() reports any that does not rather than letting the voice talk over
    the next card. Nothing on screen is timed off these words - the beat grid
    is the clock - so a line running slightly short is silence, not drift.
    """
    s = STR[lang]
    lines = {"n0": f"{B.club(fx.home_short, lang)} "
                   f"{'gegen' if lang == 'de' else 'against'} "
                   f"{B.club(fx.away_short, lang)}.",
             "n1": s["three_say"] + "."}
    for i, leg in enumerate(fx.legs):
        lines[f"l{i}"] = leg.say + "."
    conf = B._num_say(str(fx.conf), lang) if fx.conf else None
    if conf:
        lines["nc"] = (f"{conf} Prozent Konfidenz." if lang == "de"
                       else f"{conf} percent confidence.")
    return lines


#: Which beat each narration line starts on.
VO_AT = {"n1": 8, "l0": 12, "l1": 20, "l2": 28, "nc": 36}


def fits(clips: dict, room: dict) -> list[str]:
    """Which spoken lines are longer than the segment they sit in."""
    bad = []
    for key, beats_ in room.items():
        if key in clips and clips[key]["dur"] > beats_ * BEAT - 0.15:
            bad.append(f"{key}: {clips[key]['dur']:.2f}s of speech in "
                       f"{beats_ * BEAT:.2f}s of picture")
    return bad


# -------------------------------------------------------------------- glyphs
def glyph(kind: str, size: int, fill, dim: bool = False) -> Image.Image:
    """The little mark on a rung. Drawn, not an emoji - the project font has no
    emoji coverage and a missing glyph renders as a blank box, which on the one
    element that is supposed to say "goals" is worse than no icon at all."""
    key = ("bbg", kind, size, fill, dim)
    if key in P._cache:
        return P._cache[key]
    im = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    c = size / 2
    ink = fill if not dim else (150, 158, 168)
    if kind == "goal":
        d.ellipse((3, 3, size - 4, size - 4), fill=ink)
        r = size * 0.17
        d.regular_polygon((c, c, r), 5, rotation=0, fill=(12, 14, 18))
        for a in range(5):
            x = c + math.cos(math.radians(a * 72 - 90)) * size * 0.32
            y = c + math.sin(math.radians(a * 72 - 90)) * size * 0.32
            d.regular_polygon((x, y, r * 0.62), 5, rotation=36,
                              fill=(12, 14, 18))
    elif kind == "card":
        d.rounded_rectangle((size * 0.26, size * 0.12, size * 0.74,
                             size * 0.88), size * 0.10, fill=ink)
    elif kind == "corner":
        d.line([(size * 0.30, size * 0.10), (size * 0.30, size * 0.90)],
               fill=ink, width=max(3, size // 12))
        d.polygon([(size * 0.34, size * 0.16), (size * 0.84, size * 0.32),
                   (size * 0.34, size * 0.48)], fill=ink)
    elif kind == "shot":
        for i, r in enumerate((0.46, 0.30, 0.14)):
            d.ellipse((c - size * r, c - size * r, c + size * r, c + size * r),
                      outline=ink, width=max(3, size // 11),
                      fill=ink if i == 2 else None)
    elif kind == "btts":
        d.ellipse((size * 0.06, c - size * 0.20, size * 0.46, c + size * 0.20),
                  fill=ink)
        d.ellipse((size * 0.54, c - size * 0.20, size * 0.94, c + size * 0.20),
                  fill=ink)
    else:                                   # shield
        d.polygon([(c, size * 0.08), (size * 0.88, size * 0.26),
                   (size * 0.78, size * 0.80), (c, size * 0.94),
                   (size * 0.22, size * 0.80), (size * 0.12, size * 0.26)],
                  fill=ink)
    P._cache[key] = im
    return im


def _wrap(text: str, f, room: int) -> list[str]:
    out, line = [], ""
    for w in text.split():
        t = f"{line} {w}".strip()
        if f.getlength(t) <= room or not line:
            line = t
        else:
            out.append(line)
            line = w
    if line:
        out.append(line)
    return out


def rung(b: T.Brand, leg: B.Leg, live: bool) -> Image.Image:
    """One step of the progress bar, lit or not.

    THE UNLIT STATE CONTAINS NO TEXT. Not blurred text, not dimmed text -
    none. Blurring 34pt type does not hide it; it reads perfectly and hands
    the viewer the answer the whole video is built to reveal. So an unlit rung
    is a grey icon and two placeholder bars, the way a page looks before its
    content loads, and the words only ever exist in the lit copy.
    """
    key = ("bbrung", b.key, leg.disp, leg.pct, live)
    if key in P._cache:
        return P._cache[key]
    im = Image.new("RGBA", (LAD_W, LAD_H), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    dark = b.style == "dark"
    d.rounded_rectangle((0, 0, LAD_W - 1, LAD_H - 1), 26,
                        fill=(9, 11, 15, 214) if dark else (243, 240, 232, 224))
    if live:
        d.rounded_rectangle((0, 0, 7, LAD_H - 1), 4, fill=b.accent)

    gs = 62
    im.alpha_composite(glyph(leg.icon, gs, b.accent, dim=not live),
                       (26, (LAD_H - gs) // 2))
    x = 26 + gs + 20
    ink = (247, 250, 253) if dark else T.CHAR
    sub = (150, 163, 178) if dark else (120, 116, 106)

    if not live:
        # Skeleton, deliberately not words - and OPAQUE, per style.
        #
        # It used to be white at alpha 46, which is not a pale bar: ImageDraw
        # sets pixels, it does not blend them, so those two rectangles punched
        # a nearly transparent hole straight through the card. On the dark
        # brand the hole showed dark background and happened to look like a
        # faint bar. On LuxTipps, whose card is cream, it showed the same dark
        # background - two hard charcoal bars on a light card, higher contrast
        # than the real text that replaces them. verify_bbreel caught it as
        # "rung 3 already has as much detail before it lights as after", which
        # is exactly what it was.
        bar = (48, 55, 66, 255) if dark else (206, 201, 190, 255)
        d.rounded_rectangle((x, 40, x + 250, 58), 9, fill=bar)
        d.rounded_rectangle((x, 70, x + 160, 88), 9, fill=bar)
        P._cache[key] = im
        return im

    pct = f"{leg.pct}%" if leg.pct else ""
    pf = P.font(38)
    pw = pf.getlength(pct) + 20 if pct else 0
    room = LAD_W - x - 22 - pw
    size = 38
    f = P.font(size)
    while size > 22:
        rows = _wrap(leg.disp, f, room)
        if len(rows) <= 2:
            break
        size -= 2
        f = P.font(size)
    rows = _wrap(leg.disp, f, room)[:2]
    y = LAD_H // 2 - (len(rows) - 1) * (size + 6) // 2
    for r in rows:
        d.text((x, y), r, font=f, fill=ink, anchor="lm")
        y += size + 6
    if pct:
        d.text((LAD_W - 22, LAD_H // 2), pct, font=pf, fill=b.accent,
               anchor="rm")
    P._cache[key] = im
    return im


def match_card(b: T.Brand, fx: B.Fixture) -> Image.Image:
    """Pinned from the moment the fixture lands and never taken away, so the
    match is answerable at any frame the viewer happens to scroll in on."""
    key = ("bbcard", b.key, fx.id)
    if key in P._cache:
        return P._cache[key]
    cw, ch = W - 104, 214
    im = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    dark = b.style == "dark"
    d.rounded_rectangle((0, 0, cw - 1, ch - 1), 30,
                        fill=(9, 11, 15, 226) if dark else (243, 240, 232, 232))
    ink = (247, 250, 253) if dark else T.CHAR
    sub = (150, 163, 178) if dark else (120, 116, 106)

    cs = 112
    for i, url in enumerate((fx.home_logo, fx.away_logo)):
        disc = Image.new("RGBA", (cs, cs), (0, 0, 0, 0))
        dd = ImageDraw.Draw(disc)
        dd.ellipse((0, 0, cs - 1, cs - 1), fill=b.accent)
        dd.ellipse((5, 5, cs - 6, cs - 6), fill=(252, 252, 252))
        p = B.crest(url)
        if p:
            try:
                c = Image.open(p).convert("RGBA")
                k = int(cs * 0.62)
                c = c.resize((k, k), Image.LANCZOS)
                disc.paste(c, ((cs - k) // 2, (cs - k) // 2), c)
            except Exception:                             # noqa: BLE001
                pass
        im.alpha_composite(disc, (24 + int(i * cs * 0.74), (ch - cs) // 2))

    x = 24 + int(cs * 1.74) + 22
    name = f"{fx.home_short.upper()}  –  {fx.away_short.upper()}"
    size = 52
    while P.font(size).getlength(name) > cw - x - 26 and size > 26:
        size -= 2
    d.text((x, 82), name, font=P.font(size), fill=ink, anchor="lm")
    when = f"{fx.kickoff:%H:%M}  ·  {fx.league.upper()}"
    size = 32
    while P.font(size).getlength(when) > cw - x - 26 and size > 18:
        size -= 2
    d.text((x, 140), when, font=P.font(size), fill=sub, anchor="lm")
    P._cache[key] = im
    return im


_cap: dict = {}
SIZES = {"hook": 250, "big": 176, "mid": 104, "pct": 240}


def word(text: str, fill, size_key: str, emo: str | None = None) -> Image.Image:
    """A caption, outlined, with an optional emoji beside it.

    The emoji is composited as an image rather than typed into the string. Lato
    has no emoji coverage at all, so an emoji in the text argument draws a
    blank box - and worse, it draws a blank box that the stroke outlines, which
    looks deliberate. Noto Color Emoji is a bitmap font that only loads at
    109px (P.emoji does that and scales down), and it will not shape inside a
    Lato run anyway.

    It sits at 0.62 of the cap height and on the baseline of the text, not
    centred on the box: centred, a 110px square emoji beside a 104px line with
    no descenders floats visibly high.
    """
    key = (text, fill, size_key, emo)
    if key in _cap:
        return _cap[key]
    size, pad = SIZES[size_key], 34
    f = P.font(size)
    room = 900 if not emo else 900 - int(size * 0.94)
    while f.getlength(text) > room and size > 44:
        size -= 6
        f = P.font(size)
    box = f.getbbox(text, stroke_width=17)
    tw, th = box[2] - box[0], box[3] - box[1]

    es = int(size * 0.80) if emo else 0
    eim = P.emoji(emo, es) if emo else None
    gap = int(size * 0.20) if emo else 0
    ew = (eim.width + gap) if eim else 0

    im = Image.new("RGBA", (tw + pad * 2 + ew, th + pad * 2), (0, 0, 0, 0))
    ImageDraw.Draw(im).text((pad - box[0], pad - box[1]), text, font=f,
                            fill=fill + (255,), stroke_width=17,
                            stroke_fill=(0, 0, 0, 255))
    if eim:
        im.alpha_composite(eim, (pad + tw + gap,
                                 pad + th - eim.height - int(size * 0.06)))
    sh = Image.new("RGBA", im.size, (0, 0, 0, 0))
    sh.putalpha(im.getchannel("A").filter(ImageFilter.GaussianBlur(13)))
    out = Image.new("RGBA", im.size, (0, 0, 0, 0))
    out.alpha_composite(sh, (0, 13))
    out.alpha_composite(im)
    _cap[key] = out
    return out


def badge(b: T.Brand, text: str) -> Image.Image:
    """"TIPP 2/3" - a pill above the pick, so the viewer knows how many are
    left without counting rungs. The ladder already answers it; a number
    answers it in the first glance rather than the second."""
    key = ("bbbadge", b.key, text)
    if key in P._cache:
        return P._cache[key]
    f = P.font(46)
    w = int(f.getlength(text)) + 62
    im = Image.new("RGBA", (w, 78), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((0, 0, w - 1, 77), 39, fill=(0, 0, 0, 190),
                        outline=b.accent + (255,), width=4)
    d.text((w // 2, 40), text, font=f, fill=b.accent, anchor="mm")
    P._cache[key] = im
    return im


def _alpha(im: Image.Image, a: float) -> Image.Image:
    out = im.copy()
    out.putalpha(out.getchannel("A").point(lambda v: int(v * a)))
    return out


PB_W, PB_H = 560, 20


def pct_bar(b: T.Brand, pct: int, fill_to: float) -> Image.Image:
    """The bar under a percentage. Fills to `fill_to` of the true value."""
    key = ("bbpb", b.key, pct, round(fill_to, 2))
    if key in P._cache:
        return P._cache[key]
    im = Image.new("RGBA", (PB_W, PB_H), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((0, 0, PB_W - 1, PB_H - 1), PB_H // 2,
                        fill=(0, 0, 0, 150), outline=(255, 255, 255, 70),
                        width=2)
    w = int((PB_W - 6) * (pct / 100.0) * P.ease_out(fill_to))
    if w > PB_H:
        d.rounded_rectangle((3, 3, 3 + w, PB_H - 4), (PB_H - 6) // 2,
                            fill=b.accent)
    P._cache[key] = im
    return im


def furniture(b: T.Brand) -> Image.Image:
    g = Image.new("L", (W, H), 0)
    gd = ImageDraw.Draw(g)
    for y in range(H):
        top = max(0.0, 1 - y / 640) * 158
        bot = max(0.0, (y - 980) / (H - 980)) * 128
        gd.line([(0, y), (W, y)], fill=int(min(205, top + bot)))
    col = Image.new("L", (W, H), 0)
    cd = ImageDraw.Draw(col)
    for x in range(600):
        cd.line([(x, LAD_Y - 70), (x, LAD_Y + 2 * LAD_STEP + LAD_H + 70)],
                fill=int(88 * (1 - x / 600)))
    col = col.filter(ImageFilter.GaussianBlur(70))
    g.paste(ImageChops.lighter(g, col))
    im = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    im.paste((0, 0, 0, 255), (0, 0, W, H), g)
    im.alpha_composite(b.disc(96), (56, 128))
    return im


# -------------------------------------------------------------------- footage
def clip_pool() -> list[pathlib.Path]:
    """His own clips if he has sent any, otherwise the royalty-free set.

    `broll/custom/` wins outright rather than being mixed in: half a reel of
    real match footage and half of a stock warm-up looks like a mistake, not a
    style. Drop files in, they are the footage; take them out, it falls back.
    """
    custom = sorted((BROLL / "custom").glob("*.mp4"))
    if custom:
        return custom
    pool = sorted(p for p in BROLL.glob("*.mp4") if p.stem not in DROP)
    if not pool:
        raise SystemExit(f"no footage in {BROLL} - run fetch_broll.sh, or put "
                         f"his clips in {BROLL / 'custom'}")
    return pool


#: Pulled out of the free pool after looking at every clip's own frames rather
#: than at its filename. Both are called "soccer" by the stock library and
#: neither reads as football on screen: 4337 is the Manhattan skyline behind a
#: park pitch, and -30 is an empty stand behind a blue athletics track. Under a
#: DFB-Pokal pick they land as a mistake.
#:
#: This does not fix the pool, and pretending it does would be the wrong
#: lesson. What is left is still park football - bibs, chain-link fences,
#: phone-height cameras - and no arrangement of it looks like the Allianz
#: Arena. That is his complaint and he is right about it. The two real answers
#: are his own clips in broll/custom/, or `--bg motion`, which uses none.
DROP = {"soccer-match-with-a-view-4337",
        "goalkeeper-during-a-soccer-match-30"}

OVER = 1.26

_MOTION: dict = {}


def motion_layers(b: T.Brand, ow: int, oh: int):
    """The pieces of the drawn background, built once.

    WHY THIS EXISTS. He has said twice that the stock clips look like stock
    clips, and he is right - a generic warm-up drill under a Bundesliga pick
    fools nobody. He wants broadcast highlights instead, which I am not going
    to source: it is his ad account and his brand the strike lands on, and the
    edits people suggest for hiding a broadcaster's logo are exactly what the
    rights holders' matching runs on.

    So this is the third option, and it is the one that is actually used by
    most of the accounts in his own reference feed: no footage at all. A drawn
    floodlit stadium, a brand wash, a light sweep that crosses the frame, and a
    glow that pulses on the beat. It cannot look like cheap stock because it is
    not stock, and it cannot get anybody struck. `--bg motion`.

    Everything here is precomputed and the per-frame work is three numpy adds -
    compositing this with PIL every frame cost more than decoding video did.
    """
    key = (b.key, ow, oh)
    if key in _MOTION:
        return _MOTION[key]

    # Blurred and taken down hard, and that is the whole difference between a
    # background and a picture. P.stadium draws a legible floodlit ground -
    # correct for a poster, wrong here, where a bright green pitch band cut
    # straight through the middle of the frame and competed with the ladder
    # sitting on top of it. Blurred it becomes light and depth instead of
    # scenery, which is what a caption needs under it.
    base = P.stadium(ow, oh, seed=11).convert("RGB")
    base = base.filter(ImageFilter.GaussianBlur(ow / 110))
    base = Image.blend(base, Image.new("RGB", (ow, oh), (6, 8, 12)), 0.42)
    base = Image.blend(base, Image.new("RGB", (ow, oh), b.accent), 0.13)

    # A slanted band, twice the width so a full pass is one slice of one image.
    sweep = Image.new("L", (ow * 2, oh), 0)
    ImageDraw.Draw(sweep).polygon(
        [(0, oh), (int(ow * 0.34), oh), (int(ow * 0.34) + int(ow * 0.42), 0),
         (int(ow * 0.42), 0)], fill=255)
    sweep = sweep.filter(ImageFilter.GaussianBlur(ow / 9))

    # The pulse: a wide soft ellipse low in the frame, where the ladder and the
    # captions are, so a hit lifts the graphics rather than the sky.
    pulse = Image.new("L", (ow, oh), 0)
    ImageDraw.Draw(pulse).ellipse(
        (int(ow * 0.02), int(oh * 0.40), int(ow * 0.98), int(oh * 0.96)),
        fill=255)
    pulse = pulse.filter(ImageFilter.GaussianBlur(ow / 7))

    out = (np.asarray(base, np.int16),
           np.asarray(sweep, np.float32) / 255.0,
           np.asarray(pulse, np.float32) / 255.0,
           np.array(b.accent, np.float32))
    _MOTION[key] = out
    return out


def motion_frames(b: T.Brand, n: int, b0: int, hits: list[float], ow: int,
                  oh: int, si: int = 0):
    """`n` frames of drawn background, starting at beat `b0`.

    Mirrored on alternate shots. With one continuous background there is
    nothing to cut BETWEEN, and measured on the first render the drift alone
    left three consecutive shots looking identical - the first 1.6 s of the
    reel read as a still. A horizontal flip costs one numpy view and changes
    every pixel of the frame, which is what a cut is.
    """
    base, sweep, pulse, accent = motion_layers(b, ow, oh)
    if si % 2:
        base, sweep, pulse = base[:, ::-1], sweep[:, ::-1], pulse[:, ::-1]
    for k in range(n):
        t = (b0 * FPB + k) / FPS
        # One full pass of the sweep every four bars, so it never repeats
        # inside a shot and never sits still inside one either.
        off = int((t / (16 * BEAT)) % 1.0 * ow)
        lit = 0.0
        for ht in hits:
            dt = t - ht
            if 0 <= dt < 0.45:
                lit = max(lit, (1 - dt / 0.45) ** 2)
        frame = base + (sweep[:, off:off + ow, None] * 46).astype(np.int16)
        if lit > 0.01:
            frame = frame + (pulse[:, :, None] * (lit * 0.22)
                             * accent).astype(np.int16)
        yield np.clip(frame, 0, 255).astype(np.uint8)


def bg_frames(src: pathlib.Path, n: int, seed: int):
    ow, oh = int(W * OVER), int(H * OVER)
    #: A different second of the clip each time it is reused, so a pool of four
    #: files under fourteen shots does not read as four repeats.
    start = (seed * 3.7) % 9.0
    p = subprocess.Popen(
        ["ffmpeg", "-v", "error", "-ss", f"{start:.2f}", "-stream_loop", "-1",
         "-i", str(src), "-an",
         "-vf", f"fps={FPS},crop=ih*9/16:ih,scale={ow}:{oh},"
                # Lifted, not darkened. The gradient in furniture() already
                # takes the top and bottom down by a lot for the text to sit
                # on; darkening the source as well left the middle of the
                # frame - the only part actually showing football - muddy.
                "eq=brightness=0.03:saturation=1.24:contrast=1.12",
         "-frames:v", str(n), "-f", "rawvideo", "-pix_fmt", "rgb24", "-"],
        stdout=subprocess.PIPE)
    size = ow * oh * 3
    try:
        for _ in range(n):
            raw = p.stdout.read(size)
            if len(raw) < size:
                break
            yield np.frombuffer(raw, np.uint8).reshape(oh, ow, 3)
    finally:
        p.stdout.close()
        p.wait()


# ---------------------------------------------------------------------- audio
def track(fx: B.Fixture, lang: str, pl: dict, vo: bool,
          path: pathlib.Path) -> tuple[pathlib.Path, list[str]]:
    """Bed + hits (+ narration). Returns the wav and anything that did not fit."""
    bed = M.build(BPM, BARS)
    sr = bed.sr
    warn: list[str] = []

    for at in pl["hits"]:
        bed.put(M.impact(), at * BEAT - 0.02, 0.55)
        bed.put(M.riser(0.55), at * BEAT - 0.55, 0.30)
    for c in CUTS[1:]:
        bed.put(M.whoosh(), c * BEAT - 0.16, 0.24)

    mix = bed.mix.copy()
    if vo:
        lines = narration(fx, lang)
        clips = N._synth(lang, lines, f"bbreel-{fx.id}-{lang}")
        room = {"n1": 4, "l0": 8, "l1": 8, "l2": 8, "nc": 8}
        warn = fits(clips, room)
        # The bed steps back under the voice rather than the voice being
        # pushed over it - a bed at full level with a TTS read on top is the
        # single most common way this kind of video ends up unintelligible.
        for key, at in VO_AT.items():
            if key not in clips:
                continue
            with wave.open(clips[key]["file"]) as w:
                a = np.frombuffer(w.readframes(w.getnframes()), np.int16)
                vsr = w.getframerate()
            if vsr != sr:
                x = np.interp(np.arange(0, len(a), vsr / sr),
                              np.arange(len(a)), a).astype(np.float32)
            else:
                x = a.astype(np.float32)
            x /= 32768.0
            i = int(at * BEAT * sr)
            n = min(len(x), len(mix) - i)
            if n <= 0:
                continue
            duck = np.ones(n, dtype=np.float32) * 0.42
            mix[i:i + n] = mix[i:i + n] * duck + x[:n] * 1.5

    mix = np.tanh(mix * 1.1).astype(np.float32)
    M.write(mix, path)
    return path, warn


# ----------------------------------------------------------------------- bake
def render(brand_key: str, fx: B.Fixture, vo: bool, amount: int = 1000,
           bg: str = "clips") -> pathlib.Path:
    b = T.BRANDS[brand_key]
    lang = b.lang
    pl = beats(fx, lang, amount)
    total = BARS * 4 * FPB
    OUT.mkdir(parents=True, exist_ok=True)
    tag = f"{brand_key}-{fx.slug}" + ("-motion" if bg == "motion" else "")
    wav, warn = track(fx, lang, pl, vo, OUT / "vo" / f"{tag}.wav")
    for w in warn:
        print(f"  !! narration overruns its segment - {w}")

    manifest = {"fps": FPS, "bpm": BPM, "fpb": FPB, "bars": BARS,
                "frames": total, "lang": lang, "brand": brand_key,
                "fixture": {"id": fx.id, "home": fx.home_short,
                            "away": fx.away_short, "league": fx.league,
                            "kickoff": fx.kickoff.isoformat(),
                            "conf": fx.conf, "url": fx.url,
                            "legs": [{"disp": g.disp, "say": g.say,
                                      "pct": g.pct, "icon": g.icon}
                                     for g in fx.legs]},
                "cuts": CUTS, "vo": vo, "bg": bg, **pl}
    (OUT / "vo" / f"{tag}.json").write_text(
        json.dumps(manifest, indent=1, ensure_ascii=False), encoding="utf-8")

    out = OUT / f"{brand_key}-bb-{tag.split('-', 1)[1]}.mp4"
    enc = subprocess.Popen(
        ["ffmpeg", "-y", "-loglevel", "error",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}",
         "-framerate", str(FPS), "-i", "-", "-i", str(wav),
         "-c:a", "aac", "-b:a", "160k", "-shortest",
         "-c:v", "libx264", "-preset", "medium", "-crf", "20",
         "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(out)],
        stdin=subprocess.PIPE)

    fur = furniture(b)
    fill = CAP_FILL[brand_key]
    card = match_card(b, fx)
    rows = [(rung(b, g, False), rung(b, g, True)) for g in fx.legs]
    pool = clip_pool() if bg == "clips" else []
    ow, oh = int(W * OVER), int(H * OVER)

    shots = [(CUTS[i], CUTS[i + 1] - CUTS[i]) for i in range(len(CUTS) - 1)]
    shots.append((CUTS[-1], BARS * 4 - CUTS[-1]))
    hits = [h * BEAT for h in pl["hits"]]

    for si, (b0, nb) in enumerate(shots):
        n = nb * FPB
        if bg == "clips":
            src = pool[si % len(pool)]
            gen = bg_frames(src, n, si)
            src_name = src.name
        else:
            # No footage to cut between, so the cut is carried entirely by the
            # camera: the drift direction flips every shot (d0/d1 below) and
            # the punch-in resets. Both are real picture changes on the beat,
            # which is what the edit claims and what verify_bbreel measures.
            gen = motion_frames(b, n, b0, hits, ow, oh, si)
            src_name = "motion"
        last = None
        d0, d1 = (0.10, 0.90) if si % 2 == 0 else (0.90, 0.10)
        for k in range(n):
            arr = last = next(gen, last)
            if arr is None:
                raise SystemExit(f"shot {si}: no frames from {src_name}")
            f_abs = b0 * FPB + k
            t = f_abs / FPS
            u = k / max(n - 1, 1)

            # --- camera: drift, plus a decaying shake off the nearest hit
            a = d0 + (d1 - d0) * u
            sx, sy = 0, 0
            for ht in hits:
                dt = t - ht
                if 0 <= dt < 0.34:
                    e = (1 - dt / 0.34) ** 2
                    sx += int(math.sin(dt * 96) * 26 * e)
                    sy += int(math.cos(dt * 78) * 18 * e)
            # Every cut lands zoomed in by 8.5% and settles back over 0.4 s.
            # `k` restarts at each shot, so the punch is on the cut by
            # construction rather than by a timing calculation that could drift
            # off the beat grid. It is the cheapest thing in this file that
            # makes a cut feel like a cut rather than a slide change.
            z = 1 + 0.085 * (1 - P.ease_out(min(1.0, k / (FPS * 0.40))))
            cw, ch_ = int(W / z), int(H / z)
            x = min(max(int((ow - cw) * a) + sx, 0), ow - cw)
            y = min(max(int((oh - ch_) * (1 - a)) + sy, 0), oh - ch_)
            frame = Image.fromarray(arr[y:y + ch_, x:x + cw])
            if (cw, ch_) != (W, H):
                frame = frame.resize((W, H), Image.BILINEAR)
            frame = frame.convert("RGBA")
            # The impact flash goes on the FOOTAGE, before any graphic is laid
            # over it. Composited last and in the brand colour it washed the
            # entire frame - card, ladder and caption included - orange for
            # three frames, which reads as a rendering fault rather than a hit.
            # White, weaker, shorter, and underneath everything that has to
            # stay legible.
            for ht in hits:
                dt = t - ht
                if 0 <= dt < 0.11:
                    k2 = (1 - dt / 0.11) ** 2
                    frame.alpha_composite(
                        Image.new("RGBA", (W, H), (255, 255, 255,
                                                   int(58 * k2))))
                    break
            frame.alpha_composite(fur)

            # --- the match card, from the fixture bar onward
            if f_abs >= 8 * FPB:
                s = min(1.0, (t - 8 * BEAT) / 0.24)
                dy = int((1 - P.ease_out(s)) * -80)
                lay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
                lay.alpha_composite(card, (52, CARD_Y + dy))
                if s < 1:
                    lay.putalpha(lay.getchannel("A").point(
                        lambda v: int(v * s)))
                frame.alpha_composite(lay)

                for ri, (dim, live) in enumerate(rows):
                    ry = LAD_Y + ri * LAD_STEP
                    lt = pl["rungs"][ri] * BEAT
                    prog = (t - lt) / 0.26
                    if prog <= 0:
                        frame.alpha_composite(_alpha(dim, s), (LAD_X, ry))
                    elif prog >= 1:
                        frame.alpha_composite(live, (LAD_X, ry))
                    else:
                        # out, then in. The two states carry different pixels
                        # entirely - a skeleton and a sentence - so crossing
                        # them over draws both and reads as a fault.
                        if prog < 0.4:
                            frame.alpha_composite(
                                _alpha(dim, 1 - P.ease_out(prog / 0.4)),
                                (LAD_X, ry))
                        else:
                            e = P.ease_out((prog - 0.4) / 0.6)
                            sc = 1 + 0.09 * (1 - e)
                            im = live.resize((int(live.width * sc),
                                              int(live.height * sc)),
                                             Image.BILINEAR)
                            frame.alpha_composite(
                                _alpha(im, e),
                                (LAD_X - (im.width - live.width) // 2,
                                 ry - (im.height - live.height) // 2))

            # --- which pick we are on, so "how many left" is one glance
            if 12 * FPB <= f_abs < 36 * FPB:
                i = min(len(fx.legs) - 1, (f_abs // FPB - 12) // 8)
                bi = badge(b, f"{STR[lang]['tip']} {i + 1}/{len(fx.legs)}")
                # Between the match card and the ladder. Centred at caption
                # height it sat on top of the second rung - the ladder runs
                # x 52..528 and this pill is centred on 540, so they touch.
                frame.alpha_composite(bi, ((W - bi.width) // 2, CARD_Y + 250))

            # --- captions
            #
            # All of them, not the first one that matches. The hook is three
            # captions at three offsets and the old loop stopped at the first,
            # so a stacked hook would have drawn one line and silently dropped
            # the other two - including the figure the whole hook is about.
            for c in pl["caps"]:
                if not (c["at"] * BEAT <= t < c["off"] * BEAT):
                    continue
                im = word(c["text"], fill, c["size"], c.get("emo"))
                e = (t - c["at"] * BEAT) / 0.13
                sc = (0.66 + 0.46 * P.ease_out(e / 0.7) if e < 0.7
                      else 1.12 - 0.12 * P.ease_out(min(1.0, (e - 0.7) / 0.3)))
                if abs(sc - 1) > 0.005:
                    im = im.resize((max(1, int(im.width * sc)),
                                    max(1, int(im.height * sc))),
                                   Image.BILINEAR)
                cy = CAP_Y + c.get("dy", 0)
                if c["size"] == "pct":
                    cy += 40
                frame.alpha_composite(im, (max(0, W // 2 - im.width // 2),
                                           cy - im.height // 2))
                if c["size"] == "pct":
                    # The number is CORRECT from the first frame it exists;
                    # what animates is the bar under it. The first version
                    # counted the digits up from zero, which put a frame
                    # reading "0%" on screen under a betting pick - a figure
                    # that is not merely ugly but wrong, and would have been
                    # the thumbnail if the grid ever picked that frame.
                    # A bar filling cannot be misread as a claim.
                    frame.alpha_composite(
                        pct_bar(b, int(c["text"].rstrip("%")),
                                min(1.0, (t - c["at"] * BEAT) / 0.50)),
                        ((W - PB_W) // 2, cy + im.height // 2 + 26))

            enc.stdin.write(frame.convert("RGB").tobytes())

    enc.stdin.close()
    enc.wait()
    print(f"  {out.name}  {total}f  {total / FPS:.1f}s  "
          f"{len(fx.legs)} legs  {fx.conf}%")
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--brand", choices=list(T.BRANDS) + ["both"], default="both")
    ap.add_argument("--n", type=int, default=1, help="how many fixtures")
    ap.add_argument("--fixture", type=int, help="a specific post id")
    ap.add_argument("--vo", action="store_true", help="add a spoken layer")
    ap.add_argument("--all", action="store_true",
                    help="allow fixtures that have already kicked off")
    ap.add_argument("--amount", type=int, default=1000,
                    help="the figure in the hook line")
    ap.add_argument("--bg", choices=("clips", "motion"), default="clips",
                    help="stock/his footage, or the drawn background")
    a = ap.parse_args()
    for k in (list(T.BRANDS) if a.brand == "both" else [a.brand]):
        lang = T.BRANDS[k].lang
        fxs = B.load(lang, upcoming=not a.all)
        if a.fixture:
            fxs = [f for f in fxs if f.id == a.fixture]
        if not fxs:
            raise SystemExit("no upcoming fixture with a usable combo")
        print(f"{k}:")
        for fx in fxs[:a.n]:
            render(k, fx, a.vo, a.amount, a.bg)


if __name__ == "__main__":
    main()
